"""
This is a setup.py script generated by py2applet

Usage:
    python3 setup.py py2app --matplotlib-backends TkAgg
    Results in 131.9 MB app w/o "import os"
    Results in 135.2 MB app w/ "import os"

    python3 setup.py py2app
    Results in 207.9 MB app

    without PIL:
        CRASH
    with from PIL import Image:
        CRASH
    with python3 setup.py py2app --matplotlib-backends TkAgg --includes PIL.Image:
        CRASH
"""

from setuptools import setup

APP = ['LinearPlot.py']
DATA_FILES = []
OPTIONS = {"packages": ["PIL"]}

setup(
    name="Linear Plot",
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
